# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72da745d9078506e85f28b092e64780bdd939b0b42b0a7b2ff7b7387320749af7e940f88d34f75b269556280c8d57d6ded72cdd96ba53fe7648ba0507aaa3682

test:
  secret_key_base: 5fb311b564e1ed8801cf2012a4eea605b12c3ae7026f4db50cfc7aa90e565db22c13c1f4bc229c320ccae55d930dcb70f8ae6768a537e63786a6b8fe35fc8a6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
